config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'tweets#index'
  get    'tweets'          => 'tweets#index' #ツイート一覧画面
  get    'tweets/new'      => 'tweets#new' #ツイート投稿画面
  post   'tweets'          => 'tweets#create' #ツイート投稿機能
  get    'users/:id'       => 'users#show'
  delete 'tweets/:id'      => 'tweets#destroy'
  get    'tweets/:id/edit' => 'tweets#edit'
  patch  'tweets/:id'      => 'tweets#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: :index
  
  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
  end

  def create
    Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id) #tweets_params呼び出し(返り値を取得)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
    tweet.update(tweet_params)
    end
  end

  private
  def tweet_params
    params.permit(:image, :text) #ビューから送られたparamsの中から、:image,:textとそのバリューのセットだけを残し、新たなハッシュを生成→これが返り値
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @tweets = current_user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pigtweet</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PigTweet</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <a href="/users/<%= current_user.id %>">マイページ</a>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
          <a class="post" href="/tweets/new">推し豚を投稿する</a>
        <% else %>
            <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright PicTweet 2014.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿完了ブヒィィ！
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <%= form_tag("/tweets/#{@tweet.id}", method: :patch) do %>
    <h3>
      編集する
    </h3>
    <input placeholder="編集後の画像のURL" type="text" name="image" value=<%= @tweet.image %> >
    <textarea cols="30" name="text" placeholder="編集後の本文" rows="10"><%= @tweet.text %></textarea>
    <input type="submit" value="編集する">
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents row" >
  <% @tweets.each do |tweet| %> <%# @tweetsのレコードの数だけ繰り返し %>
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
      <% if user_signed_in? && current_user.id == tweet.user_id %>
      <div class="more">
       <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">

          <li>
            <%=  link_to '編集', "tweets/#{tweet.id}/edit", method: :get %>
          </li>

          <li>
            <%=  link_to '削除', "tweets/#{tweet.id}", method: :delete %>
          </li>
        </ul>
      </div>
      <% end %>
        <%= simple_format(tweet.text) %>
      <span class="name">
        <a href="">
          <span>投稿者</span><%= tweet.user.nickname %>
        </a>
      </span>
    </div>
    <% end %>
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<!-- <div class="contents row">
  <%= form_tag('/tweets', method: :post) do %>
    <h3>
      投稿する？
    </h3>
    <input placeholder="画像のURL" type="text" name="image">
    <textarea cols="30" name="text" placeholder="本文" rows="10"></textarea>
    <input type="submit" value="投稿する">
  <% end %>
</div> -->

<div class="contents row">
<%= form_with url: tweets_path do |f| %>
    <h3>
      投稿する？
    </h3>
<%= f.text_field :image, :placeholder => "imageURL"%>
<%= f.text_field :text, :placeholder => "text"%>
<%= f.date_select :date %>
  <%= f.label :入力内容を確認しましたか？ %>
  <%= f.check_box :checkbox, id: :samurai_checkbox,:as => :boolean%>
<%= f.submit value="投稿する"%>
  <% end %>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
      <div class="content_post" style="background-image: url(<%= tweet.image %>);">
        <%= simple_format(tweet.text) %>
      </div>
    <% end %>
  <%= paginate(@tweets) %>
</div>